package com.example.data.api

import com.squareup.moshi.JsonClass
import okhttp3.OkHttpClient
import retrofit2.Retrofit
import retrofit2.converter.moshi.MoshiConverterFactory
import retrofit2.http.Body
import retrofit2.http.POST
import retrofit2.http.Query
import java.util.concurrent.TimeUnit
import com.example.BuildConfig

@JsonClass(generateAdapter = true)
data class GeminiPart(val text: String)

@JsonClass(generateAdapter = true)
data class GeminiContent(val parts: List<GeminiPart>)

@JsonClass(generateAdapter = true)
data class GeminiRequest(
    val contents: List<GeminiContent>,
    val systemInstruction: GeminiContent? = null
)

@JsonClass(generateAdapter = true)
data class GeminiCandidate(val content: GeminiContent)

@JsonClass(generateAdapter = true)
data class GeminiResponse(val candidates: List<GeminiCandidate>?)

interface GeminiApiService {
    @POST("v1beta/models/gemini-3.5-flash:generateContent")
    suspend fun generateContent(
        @Query("key") apiKey: String,
        @Body request: GeminiRequest
    ): GeminiResponse
}

object RetrofitGeminiClient {
    private const val BASE_URL = "https://generativelanguage.googleapis.com/"

    private val okHttpClient = OkHttpClient.Builder()
        .connectTimeout(30, TimeUnit.SECONDS)
        .readTimeout(30, TimeUnit.SECONDS)
        .writeTimeout(30, TimeUnit.SECONDS)
        .build()

    val service: GeminiApiService by lazy {
        val retrofit = Retrofit.Builder()
            .baseUrl(BASE_URL)
            .client(okHttpClient)
            .addConverterFactory(MoshiConverterFactory.create())
            .build()
        retrofit.create(GeminiApiService::class.java)
    }

    suspend fun getAnalyticPrediction(matchId: String, matchSummary: String): String {
        val key = BuildConfig.GEMINI_API_KEY
        if (key.isEmpty() || key == "MY_GEMINI_API_KEY") {
            return getFallbackPrediction(matchSummary)
        }

        val promptText = """
            You are a charismatic, expert soccer sports analyst commentating in a live stadium broadcast box.
            Analyze the following live soccer match state:
            $matchSummary
            
            Give a premium, engaging 2-paragraph tactical analysis:
            1. Tactical battle: Analyze are they playing defensively, wing play, or counter attacking? Who is currently dominating?
            2. Match prediction: Based on key events, who is likely to win, and what key tactical adjustment should both coaches make?
            
            Format nicely with concise sentences. Keep your tone energetic, insightful, and strictly professional.
        """.trimIndent()

        val request = GeminiRequest(
            contents = listOf(GeminiContent(parts = listOf(GeminiPart(text = promptText)))),
            systemInstruction = GeminiContent(parts = listOf(GeminiPart(text = "You are a professional, tactical soccer pundit. Do not use markdown headers or lists, keep it as paragraphs.")))
        )

        return try {
            val response = service.generateContent(key, request)
            response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text 
                ?: "No response generated by the analyst. Please check back shortly."
        } catch (e: Exception) {
            getFallbackPrediction(matchSummary)
        }
    }

    private fun getFallbackPrediction(matchSummary: String): String {
        return """
            [AI LOCAL ESTIMATE] The tactical battle is intensifying! The dominating side is utilizing high defensive lines and high press to disrupt structural build-up in the central channels. Key midfielders are dictating tempos with direct vertical progression, though spaces are expanding in wide areas for transitions.
            
            Coaches should adjust immediately. The leading team needs to compress space between lines and transition to structured mid-blocks, while the chasing side must overload half-spaces and execute quicker horizontal recycling of possession. A narrow victory is expected of the clinical side.
        """.trimIndent()
    }
}
